### ISSUE TITLE
#01_リファクタリング

### ISSUE THREAD

**Issue by JunNagashima** [wryyy6124/digidana#5]
https://github.com/wryyy6124/digidana/blob/c903f6fa5ebd00343770bdfd638ba5efb05ccf0d/src/app/page.tsx#L23

ここもbookと同じようにしてあげたほうが良いです

**Comment by wryyy6124** [comment]
ご指摘の箇所（エラーハンドリング）修正しました！

https://github.com/wryyy6124/digidana/blob/main/src/app/page.tsx
