### ISSUE TITLE
#2_リファクタリング

### ISSUE THREAD

**Issue by JunNagashima** [wryyy6124/digidana#6]
https://github.com/wryyy6124/digidana/blob/c903f6fa5ebd00343770bdfd638ba5efb05ccf0d/src/app/page.tsx#L26
ここは削除し
https://github.com/wryyy6124/digidana/blob/c903f6fa5ebd00343770bdfd638ba5efb05ccf0d/src/app/page.tsx#L31
　のみにした方が良いです。

try/catchの外側で、から配列として持っておいて、

```
return <HomePage books={books} series={series} />
```

としてあげる方がいいです。

**Comment by wryyy6124** [comment]
@JunNagashima 
ご指摘の箇所修正しましたが、これで認識合ってますでしょうか🤔

https://github.com/wryyy6124/digidana/blob/main/src/app/page.tsx

**Comment by JunNagashima** [comment]
@wryyy6124 
少し違います！
イメージはこんな感じです！
`const supabase = supabaseServer();
const test = async () => {
  try {
    const { data: books, error: booksError } = await supabase
      .from("volumes")
      .select();

    if (booksError) {
      throw new Error(`Error fetching books data: ${booksError}`);
    }

    const { data: series, error: seriesError } = await supabase
      .from("series")
      .select();

    if (seriesError) {
      throw new Error(`Error fetching series data: ${seriesError}`);
    }

    return { books: books, series: series }
  } catch (error) {
    console.error(`Could not be obtained due to some Error: ${error}`);
    return { books: [], series: [] }
  }
}
const { books, series } = await test()
return <HomePage books={ books } series = { series } />;
`

**Comment by wryyy6124** [comment]
@JunNagashima 
ありがとうございます！

頂いた内容を参考に記載内容を変更しました
動作や挙動について問題ない事を確認しております

```
  const supabase = supabaseServer();

  const fetchListData = async (): Promise<HomePageProps> => {
    try {
      const { data: books, error: booksError } = await supabase
        .from("volumes")
        .select();

      if (booksError) {
        throw new Error(`Error fetching books data: ${booksError}`);
      }

      const { data: series, error: seriesError } = await supabase
        .from("series")
        .select();

      if (seriesError) {
        throw new Error(`Error fetching series data: ${seriesError}`);
      }

      return { books, series };
    } catch (error) {
      console.error(`Could not be obtained due to some Error: ${error}`);
      return { books: [], series: [] };
    }
  };
  const { books, series }: HomePageProps = await fetchListData();

  return <HomePage books={books} series={series} />;
```

※差分詳細
https://github.com/wryyy6124/digidana/commit/3ae92f72b53fb414742287c7862e518686f7350c
